language: ruby

sudo: required

services: docker

env:
- DOCKERFILE_LOCATION=centos-6
- DOCKERFILE_LOCATION=centos-7
- DOCKERFILE_LOCATION=centos-7-systemd
- DOCKERFILE_LOCATION=debian-7
- DOCKERFILE_LOCATION=debian-8
- DOCKERFILE_LOCATION=fedora-20
- DOCKERFILE_LOCATION=fedora-26
- DOCKERFILE_LOCATION=fedora-rawhide-systemd
- DOCKERFILE_LOCATION=ubuntu-12.04
- DOCKERFILE_LOCATION=ubuntu-12.04-upstart
- DOCKERFILE_LOCATION=ubuntu-14.04
- DOCKERFILE_LOCATION=ubuntu-14.04-upstart
- DOCKERFILE_LOCATION=ubuntu-16.04
- DOCKERFILE_LOCATION=ubuntu-17.04

script: travis_retry bundle exec rspec
